### PR TITLE
Feat/selling price to event

### PR DESCRIPTION
**Pull request by filafb**
#### What problem is this solving?

This PR adds `sellingPrice` to the object sent to pixel events. The `price` value presented currently in the object is the original price. It was a requirement from one customer in Europe that is developing a pixel app.

:eyes: @fpinhodev

#### How to test it?

Capture an `vtex:addToCart` event from a pixel app with this new version linked. The `sellingPrice`value will be presented, as shown below.

Selling Price @ add-to-cart-button

### CODE REVIEW

**Review by vitorflg — APPROVED** [review]
LGTM

**Review by victorhmp — APPROVED** [review]

**Comment by filafb** [comment]
Hi @vitorflg and @victorhmp! Our customer just asked today again about this feature. Do you know when we can have it merged? Thanks!

**Review by camilavcoutinho — APPROVED** [review]

**Comment by victorhmp** [comment]
Hi @filafb !

Sorry for the delay. We should have this merged between today and the end of the week :)

**Comment by fpinhodev** [comment]
Thanks for your help @filafb 
Keep up the great work! 🔥

**Pull request merged**
