### PR TITLE
Feature/add seller to event

### PR DESCRIPTION
**Pull request by lucaspacheco-acct**
#### What problem is this solving?

Seller is a extremely important data for market places.

#### How to test it?

In the workspace below, first click in the buy button and then type the following postal code: 05010-040 (if you type an invalid postalCode you may not be regionalize and you won't be able to add the product to cart). After the window reload, you've been regionalized and then you can click on the buy button and see a log in the console with the seller information added to the eventPixel object.

[Workspace](https://productseller--carrefourbrfood.myvtex.com/bisnaguinha-panco-300g-242012/p)

#### Screenshots or example usage:

image

### CODE REVIEW

**Review by klzns — APPROVED** [review]

**Review by klzns — CHANGES_REQUESTED** [review]
Update tests

**Comment by klzns** [comment]
@lucaspacheco-acct sorry, I should've been more clear

You can see that the action "IO app test" is failing:

image

You can check the [Details](https://github.com/vtex-apps/add-to-cart-button/pull/46/checks?check_run_id=1063415122), you can see what's wrong:

image


Also the PR is outdated with master, you can update it with a rebase with master

**Comment by lucaspacheco-acct** [comment]
@klzns tests has been updated :)

**Review by klzns — APPROVED** [review]

**Review by victorhmp — APPROVED** [review]

**Comment by klzns** [comment]
Related to https://github.com/vtex-apps/shelf/pull/236

**Comment by klzns** [comment]
Thanks @lucaspacheco-acct, I created a new PR #47 with the branch rebased, we will merge that soon. We'll continue there.

**Comment by klzns** [comment]
@allcontributors add @lucaspacheco-acct for code

**Pull request closed without merging**
