### PR TITLE
Revert "Fix/SKU selector consistency"

### PR DESCRIPTION
**Pull request by igorbrasileiro**
Reverts vtex-apps/add-to-cart-button#87

### CODE REVIEW

**Comment by IvanClementino** [comment]
Did this cause any problems? It solved ours

**Comment by igorbrasileiro** [comment]
Hello @IvanClementino yeah, at some stores the add to cart button didn't work as expected. So I deprecate, but asap i will do a fix.

**Comment by igorbrasileiro** [comment]
> Did this cause any problems? It solved ours before the revert

Hey @IvanClementino I opened a PR reverting the revert haha https://github.com/vtex-apps/add-to-cart-button/pull/92

**Comment by IvanClementino** [comment]
> > Did this cause any problems? It solved ours before the revert
> 
> Hey @IvanClementino I opened a PR reverting the revert haha #92

When are PRs merged?

**Pull request merged**
